const nx = require('@nx/eslint-plugin');
const tseslint = require('typescript-eslint');

module.exports = tseslint.config(
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  {
    // CommonJS tooling configs (webpack.config.js, etc.) use Node globals and
    // require() — they are not TypeScript source and shouldn't be linted as such.
    files: ['**/*.cjs', '**/*.js'],
    languageOptions: { sourceType: 'commonjs', globals: { require: 'readonly', module: 'writable', __dirname: 'readonly', process: 'readonly' } },
    rules: { '@typescript-eslint/no-require-imports': 'off', 'no-undef': 'off' },
  },
  {
    files: ['**/*.ts'],
    rules: {
      // Forklift rule: a service may depend only on shared libs, never on another service.
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          // Each service imports its OWN generated Prisma client from a distinct
          // node_modules/.prisma output dir (per-service clients, generated by
          // tools/prisma-foreach.js). That is not a cross-service import — allow it.
          // Matched as a regex against the literal import string (the rule's
          // allow-list falls back to RegExp.test for patterns without wildcards).
          allow: ['node_modules/\\.prisma/'],
          depConstraints: [
            { sourceTag: 'type:service', onlyDependOnLibsWithTags: ['type:util', 'type:nest-lib', 'scope:shared'] },
            { sourceTag: 'scope:shared', onlyDependOnLibsWithTags: ['scope:shared'] },
          ],
        },
      ],
    },
  },
);
